package arayuz;

import arayuz.vatandasFonksyonlari.*;
import yonetim.SuYonetimi;

public class ArayuzVatandas extends javax.swing.JFrame {

    public ArayuzVatandas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trafik = new javax.swing.JButton();
        enerji = new javax.swing.JButton();
        suRez = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vatandaş Arayüzü");

   
        trafik.setText("Trafik Durumu");
        trafik.setBackground(new java.awt.Color(70, 130, 180)); 
        trafik.setFont(new java.awt.Font("Segoe UI", 1, 16)); 
        trafik.setFocusable(false);
        trafik.setPreferredSize(new java.awt.Dimension(200, 50)); 
        trafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trafikActionPerformed(evt);
            }
        });

        enerji.setText("Enerji Durumu");
        enerji.setBackground(new java.awt.Color(34, 193, 195)); 
        enerji.setFont(new java.awt.Font("Segoe UI", 1, 16)); 
        enerji.setFocusable(false);
        enerji.setPreferredSize(new java.awt.Dimension(200, 50)); 
        enerji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enerjiActionPerformed(evt);
            }
        });

        suRez.setText("Su Durumu");
        suRez.setBackground(new java.awt.Color(255, 87, 34)); 
        suRez.setFont(new java.awt.Font("Segoe UI", 1, 16)); 
        suRez.setFocusable(false);
        suRez.setPreferredSize(new java.awt.Dimension(200, 50)); 
        suRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suRezActionPerformed(evt);
            }
        });

        jButton5.setText("Geri");
        jButton5.setBackground(new java.awt.Color(255, 204, 204)); 
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); 
        jButton5.setFocusable(false);
        jButton5.setPreferredSize(new java.awt.Dimension(200, 50)); 
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(trafik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enerji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suRez, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(trafik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enerji, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suRez, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void trafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trafikActionPerformed
        // TODO add your handling code here:
        new Trafik().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_trafikActionPerformed

    private void enerjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enerjiActionPerformed
        // TODO add your handling code here:
        new Enerji().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_enerjiActionPerformed

    private void suRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suRezActionPerformed
        // TODO add your handling code here:
        new Su().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_suRezActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArayuzVatandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArayuzVatandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArayuzVatandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArayuzVatandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArayuzVatandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton enerji;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton suRez;
    private javax.swing.JButton trafik;
    // End of variables declaration
}
