
package arayuz;

import arayuz.yoneticiFonksyonlari.*;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import kisiler.Yonetici;


public class ArayuzYonetici extends javax.swing.JFrame {


    public ArayuzYonetici() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varEkGu = new javax.swing.JButton();
        hizmetIzle = new javax.swing.JButton();
        uyari = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Arayüzü");


        varEkGu.setText("Varlık ekleme/güncelleme");
        varEkGu.setBackground(new java.awt.Color(70, 130, 180)); // Rengi özelleştir
        varEkGu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // Özel yazı tipi
        varEkGu.setFocusable(false);
        varEkGu.setPreferredSize(new java.awt.Dimension(200, 50)); // Buton boyutunu ayarla
        varEkGu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varEkGuActionPerformed(evt);
            }
        });

        hizmetIzle.setText("Hizmetleri izleme");
        hizmetIzle.setBackground(new java.awt.Color(34, 193, 195)); // Rengi özelleştir
        hizmetIzle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // Özel yazı tipi
        hizmetIzle.setFocusable(false);
        hizmetIzle.setPreferredSize(new java.awt.Dimension(200, 50)); // Buton boyutunu ayarla
        hizmetIzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hizmetIzleActionPerformed(evt);
            }
        });

        uyari.setText("Uyarılar");
        uyari.setBackground(new java.awt.Color(255, 87, 34)); // Rengi özelleştir
        uyari.setFont(new java.awt.Font("Segoe UI", 1, 16)); // Özel yazı tipi
        uyari.setFocusable(false);
        uyari.setPreferredSize(new java.awt.Dimension(200, 50)); // Buton boyutunu ayarla
        uyari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyariActionPerformed(evt);
            }
        });

        jButton5.setText("Çıkış");
        jButton5.setBackground(new java.awt.Color(255, 204, 204)); // Rengi özelleştir
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // Özel yazı tipi
        jButton5.setFocusable(false);
        jButton5.setPreferredSize(new java.awt.Dimension(200, 50)); // Buton boyutunu ayarla
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hizmetIzle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uyari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varEkGu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(16, 16, 16)
                .addComponent(varEkGu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hizmetIzle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varEkGuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varEkGuActionPerformed
        // Varlık güncelleme ekranını aç
        VarlikEkGu varlikEkGu = new VarlikEkGu();
        varlikEkGu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_varEkGuActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Çıkış işlemini onayla
        int response = JOptionPane.showConfirmDialog(
                this,
                "Çıkmak istediğinizden emin misiniz?",
                "Onayla",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.CANCEL_OPTION
            );

            if (response == JOptionPane.YES_OPTION) {
                // Uygulamayı kapat
                System.exit(0);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void hizmetIzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hizmetIzleActionPerformed
        // Open the service monitoring screen
        HizmetleriIzleme hizmet = new HizmetleriIzleme();
        hizmet.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_hizmetIzleActionPerformed

    private void uyariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyariActionPerformed
        // Open the alerts screen
        Uyarilar uyarilar = new Uyarilar();
        uyarilar.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_uyariActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArayuzYonetici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton hizmetIzle;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton uyari;
    private javax.swing.JButton varEkGu;
    // End of variables declaration
}