package arayuz;

import kisiler.Yonetici;
import javax.swing.JOptionPane;
import yonetim.*;

public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gAd = new javax.swing.JTextField();
        Ygirişi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        gSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Yap");

        jLabel1.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        jLabel2.setText("Şifre:");

        gAd.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        gAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gAdActionPerformed(evt);
            }
        });

        Ygirişi.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        Ygirişi.setText("Giriş");
        Ygirişi.setBackground(new java.awt.Color(102, 204, 255));
        Ygirişi.setForeground(new java.awt.Color(255, 255, 255));
        Ygirişi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YgirişiActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        jButton5.setText("Geri");
        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        gSifre.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        gSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSifreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ygirişi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gAd, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(gSifre))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Ygirişi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YgirişiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YgirişiActionPerformed
    try {
        int sifre = Yonetici.getSifre();
        String ad = Yonetici.getAd();

        // Beklenen kimlik bilgileriyle girişin eşleşip eşleşmediğini kontrol et
        if (sifre == Integer.parseInt(gSifre.getText()) && ad.equals(gAd.getText())) {
            new SuYonetimi().uyar();
            new TrafikYonetimi().uyar();
            new EnerjiYonetimi().uyar();
 
            ArayuzYonetici yntc = new ArayuzYonetici();
            yntc.setVisible(true);
            setVisible(false);
        } else if(gAd.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Eksik bilgi: Lütfen tüm alanları doldurun!", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);        
        } else {
            JOptionPane.showMessageDialog(null, "Hatali sifre ya da yanlis ad", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Şifre sade ınt 
        JOptionPane.showMessageDialog(null, "Sifre sadece sayi olmalidir!", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);
    } catch (NullPointerException e) {
        // Boş yerler için
        JOptionPane.showMessageDialog(null, "Eksik bilgi: Lütfen tüm alanları doldurun!", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // diger hatalar icin
        JOptionPane.showMessageDialog(null, "Bilinmeyen bir hata oluştu: ", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_YgirişiActionPerformed

    private void gAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gAdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void gSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gSifreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ygirişi;
    private javax.swing.JTextField gAd;
    private javax.swing.JPasswordField gSifre;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
