
package arayuz;

import javax.swing.JOptionPane;


public class Main extends javax.swing.JFrame {


    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        vatandas = new javax.swing.JButton();
        yonetici = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Menü");

        vatandas.setText("Vatandaş");
        vatandas.setBackground(new java.awt.Color(100, 181, 246)); // Yeni renk
        vatandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // Font değişikliği
        vatandas.setFocusable(false);
        vatandas.setPreferredSize(new java.awt.Dimension(150, 40)); // Boyutlandırma
        vatandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandasActionPerformed(evt);
            }
        });

        yonetici.setText("Yönetici");
        yonetici.setBackground(new java.awt.Color(255, 82, 82)); // Yeni renk
        yonetici.setFont(new java.awt.Font("Segoe UI", 1, 14)); // Font değişikliği
        yonetici.setFocusable(false);
        yonetici.setPreferredSize(new java.awt.Dimension(150, 40)); // Boyutlandırma
        yonetici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiActionPerformed(evt);
            }
        });

        jButton1.setText("Çıkış yap");
        jButton1.setBackground(new java.awt.Color(255, 204, 204)); // Yeni renk
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // Font değişikliği
        jButton1.setFocusable(false);
        jButton1.setPreferredSize(new java.awt.Dimension(150, 40)); // Boyutlandırma
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(yonetici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vatandas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(yonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vatandas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vatandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandasActionPerformed
        // TODO add your handling code here:
        ArayuzVatandas vatandas = new ArayuzVatandas();
        vatandas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_vatandasActionPerformed

    private void yoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_yoneticiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Çıkmak istediğinizden emin misiniz?",
                "Onayla",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.CANCEL_OPTION
            );

            if (response == JOptionPane.YES_OPTION) {
                // kullanici cikmak istiyor
                System.exit(0);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton vatandas;
    private javax.swing.JButton yonetici;
    // End of variables declaration
}
