/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arayuz.yoneticiFonksyonlari.varlikIslemleri;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import varliklar.Varlik;
import varliklar.Arac;
import varliklar.araclar.ElektrikliArac;
import varliklar.araclar.Motosiklet;
import varliklar.araclar.Otobus;
import varliklar.araclar.Otomobil;
import yonetim.TrafikYonetimi;

public class AracListesi extends javax.swing.JFrame {

    DefaultTableModel aracListesiModel = new DefaultTableModel();
    ArrayList<Arac> araclar = Varlik.getAraclar();
    /**
     * Creates new form AracListesi
     */
    public AracListesi() {
        initComponents();
        elekArac.setVisible(false);
        aracListesiModel = (DefaultTableModel) aracList.getModel();

        // Add rows to the table model
        for (Arac arac : araclar){
            aracListesiModel.addRow(new Object[]{arac.getIsim(),arac.getKonum(), arac.getKapasite(), arac.getTuketim(), arac.getTip()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        aracList = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aKapasite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aTuketim = new javax.swing.JTextField();
        aGun = new javax.swing.JButton();
        aIsim = new javax.swing.JTextField();
        aSil = new javax.swing.JButton();
        aKonum = new javax.swing.JComboBox<>();
        elekArac = new javax.swing.JPanel();
        istasyon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sarj = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Geri");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aracList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isim", "Konum", "Kapasite", "Tüketim", "Tip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        aracList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aracListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(aracList);

        jButton6.setText("Geri");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Isim         :");

        jLabel3.setText("Konum    :");

        jLabel4.setText("Kapasite :");

        jLabel5.setText("Tüketim  :");

        aGun.setText("Güncelle");
        aGun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aGunActionPerformed(evt);
            }
        });

        aIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aIsimActionPerformed(evt);
            }
        });

        aSil.setText("Sil");
        aSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSilActionPerformed(evt);
            }
        });

        aKonum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        elekArac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        istasyon.setText("İstasyona git");
        istasyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istasyonActionPerformed(evt);
            }
        });

        jLabel1.setText("Şarj    :");

        javax.swing.GroupLayout elekAracLayout = new javax.swing.GroupLayout(elekArac);
        elekArac.setLayout(elekAracLayout);
        elekAracLayout.setHorizontalGroup(
            elekAracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elekAracLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sarj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(istasyon)
                .addGap(15, 15, 15))
        );
        elekAracLayout.setVerticalGroup(
            elekAracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elekAracLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(elekAracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sarj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(istasyon))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elekArac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(aKapasite)
                                            .addComponent(aTuketim, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aIsim)
                                            .addComponent(aKonum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aGun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(aSil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aIsim)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aKonum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aKapasite)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aTuketim)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aGun, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(aSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elekArac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AracEkleme aracEkleme = new AracEkleme();
        aracEkleme.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void aGunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aGunActionPerformed
        // TODO add your handling code here:
        int selectedRow = aracList.getSelectedRow();
        if (selectedRow != -1) {
            try{
                Arac arac = null;
                String isim = aIsim.getText();
                int konum =  Integer.parseInt(aKonum.getSelectedItem().toString());
                int kapasite =  Integer.parseInt(aKapasite.getText());
                float tuketim =  Float.parseFloat(aTuketim.getText());

                if (isim == null || isim.trim().isEmpty())
                    throw new IllegalArgumentException("Araç ismi boş olamaz!"); // Bina ismi eksik veya yanlış girilmiş

                if (kapasite <= 0) 
                    throw new IllegalArgumentException("Kapasite 0 veya negatif olamaz!"); // Kapasite hatalı

                if (tuketim < 0) 
                    throw new IllegalArgumentException("Araç tüketimi negatif olamaz!"); // Tüketim değerleri doğru değil
                
                switch ((String) aracListesiModel.getValueAt(selectedRow,4)) {
                    case "Otobüs" -> arac = new Otobus(isim, konum, kapasite, tuketim);
                    case "Otomobil" -> arac = new Otomobil(isim, konum, kapasite, tuketim);
                    case "Motosiklet" -> arac = new Motosiklet(isim, konum, kapasite, tuketim);
                    case "Elektrikli araç" -> arac = new ElektrikliArac(isim, konum, kapasite, tuketim);
                    default -> throw new IllegalArgumentException("Araç türü geçersiz!"); // Geçersiz bina türü hatası
                }
                int eskiKonum = Integer.parseInt((String) aKonum.getSelectedItem());  
                int yeniKonum = Integer.parseInt(aracListesiModel.getValueAt(selectedRow, 1).toString());
                TrafikYonetimi.bolgeler.put(eskiKonum, TrafikYonetimi.bolgeler.get(eskiKonum) + 1);
                TrafikYonetimi.bolgeler.put(yeniKonum, TrafikYonetimi.bolgeler.get(yeniKonum) - 1);
                araclar.remove(araclar.size() - 1);
                araclar.set(selectedRow, arac);
                JOptionPane.showMessageDialog(this, "Araç başarıyla güncellendi", "Başarılı Işlem", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                // Sayısal bir değer beklenirken geçersiz bir giriş yapıldığında
                JOptionPane.showMessageDialog(this, "Lütfen geçerli bir sayı girin!", "Hata", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                // Geçersiz bina türü gibi durumlarda
                JOptionPane.showMessageDialog(this, e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Diğer beklenmeyen hatalar
                JOptionPane.showMessageDialog(this, "Bilinmeyen bir hata oluştu", "Hata", JOptionPane.ERROR_MESSAGE);
            }
                
                aracListesiModel.setRowCount(0); // Clear the table

                for (Arac e : araclar) {
                    aracListesiModel.addRow(new Object[] {
                        e.getIsim(),
                        e.getKonum(),
                        e.getKapasite(),
                        e.getTuketim(),
                        e.getTip()
                    });
                }
            } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir satır seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_aGunActionPerformed

    private void aIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aIsimActionPerformed

    private void aracListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracListMouseClicked
        // TODO add your handling code here:
        int selectedRow = aracList.getSelectedRow();
        if (selectedRow != -1) {
            aIsim.setText(aracListesiModel.getValueAt(selectedRow, 0).toString());
            aKonum.setSelectedItem(aracListesiModel.getValueAt(selectedRow, 1).toString());
            aKapasite.setText(aracListesiModel.getValueAt(selectedRow, 2).toString());
            aTuketim.setText(aracListesiModel.getValueAt(selectedRow, 3).toString());
            
            Arac arac = araclar.get(selectedRow);
            if(arac instanceof ElektrikliArac elektrikliArac){
                sarj.setText(String.valueOf("%" + elektrikliArac.getSarj()));
                elekArac.setVisible(true);
                if(elektrikliArac.getSarj() != 100)
                    istasyon.setVisible(true);
                else
                    istasyon.setVisible(false);
                    
            }
            else
                elekArac.setVisible(false);
        }
    }//GEN-LAST:event_aracListMouseClicked

    private void aSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSilActionPerformed
        // TODO add your handling code here:
        int selectedRow = aracList.getSelectedRow();
        if (selectedRow != -1) {
            int konum = Integer.parseInt(aKonum.getSelectedItem().toString());
            TrafikYonetimi.bolgeler.put(konum, TrafikYonetimi.bolgeler.get(konum) - 1);
            araclar.remove(selectedRow);
            aracListesiModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Araç başarıyla silinmiştir!", "Başarılı Işlem", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir satır seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aSilActionPerformed

    private void istasyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istasyonActionPerformed
        // TODO add your handling code here:
        int selectedRow = aracList.getSelectedRow();
        ElektrikliArac elektrikliArac = (ElektrikliArac) araclar.get(selectedRow);
        elektrikliArac.setSarj(100);
        istasyon.setVisible(false);
        sarj.setText(String.valueOf("%" + elektrikliArac.getSarj()));
        JOptionPane.showMessageDialog(this, "Aracın şarjı dolmuştur!", "Şarj", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_istasyonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AracListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AracListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AracListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AracListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AracListesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aGun;
    private javax.swing.JTextField aIsim;
    private javax.swing.JTextField aKapasite;
    private javax.swing.JComboBox<String> aKonum;
    private javax.swing.JButton aSil;
    private javax.swing.JTextField aTuketim;
    private javax.swing.JTable aracList;
    private javax.swing.JPanel elekArac;
    private javax.swing.JButton istasyon;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel sarj;
    // End of variables declaration//GEN-END:variables
}
