/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arayuz.yoneticiFonksyonlari.varlikIslemleri;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import varliklar.Enerjikaynagi;
import varliklar.Varlik;
import varliklar.enerjiKaynaklari.Fosil;
import varliklar.enerjiKaynaklari.Gunes;
import varliklar.enerjiKaynaklari.Nukleer;
import varliklar.enerjiKaynaklari.Ruzgar;

public class EnerjiKaynaklariListesi extends javax.swing.JFrame {

    DefaultTableModel kaynakListesiModel = new DefaultTableModel();
    ArrayList<Enerjikaynagi> enerjikaynaklari = Varlik.getEnerjiKaynaklar();
    /**
     * Creates new form EnerjiKaynaklariListesi
     */
    public EnerjiKaynaklariListesi() {
        initComponents();
        
        kaynakListesiModel = (DefaultTableModel) kaynakList.getModel();

        // Add rows to the table model
        for (Enerjikaynagi kaynak : enerjikaynaklari){
            kaynakListesiModel.addRow(new Object[]{kaynak.getIsim(),kaynak.getKonum(), kaynak.getKapasite(), kaynak.getUretim(), kaynak.getTip()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        eKapasite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uretim = new javax.swing.JTextField();
        eEkle = new javax.swing.JButton();
        eIsim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eKonum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        kaynakList = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        eKapasite1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uretim1 = new javax.swing.JTextField();
        eGun = new javax.swing.JButton();
        eIsim1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eKonum1 = new javax.swing.JComboBox<>();
        eSil = new javax.swing.JButton();

        jLabel4.setText("Kapasite         :");

        jLabel5.setText("Üretim            :");

        eEkle.setText("Güncelle");
        eEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEkleActionPerformed(evt);
            }
        });

        eIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIsimActionPerformed(evt);
            }
        });

        jLabel2.setText("Isim                 :");

        jLabel3.setText("Konum            :");

        eKonum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKonumActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kaynakList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isim", "Konum", "Kapasite", "Üretim", "Tip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kaynakList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaynakListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kaynakList);

        jButton6.setText("Geri");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Kapasite         :");

        jLabel7.setText("Üretim            :");

        uretim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uretim1ActionPerformed(evt);
            }
        });

        eGun.setText("Güncelle");
        eGun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eGunActionPerformed(evt);
            }
        });

        eIsim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIsim1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Isim                 :");

        jLabel9.setText("Konum            :");

        eKonum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        eSil.setText("Sil");
        eSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eKapasite1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uretim1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eIsim1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(eKonum1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(eGun, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eIsim1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eKonum1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eKapasite1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uretim1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eGun, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(eSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new EnerjiKaynagiEkleme().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void eEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEkleActionPerformed

    }//GEN-LAST:event_eEkleActionPerformed

    private void eIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIsimActionPerformed

    private void eKonumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKonumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eKonumActionPerformed

    private void eGunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eGunActionPerformed
        // TODO add your handling code here:
        int selectedRow = kaynakList.getSelectedRow();
        if (selectedRow != -1) {
            try {
                Enerjikaynagi kaynak = null;
                String isim = eIsim1.getText();
                int konum =  Integer.parseInt(eKonum1.getSelectedItem().toString());
                int kapasite =  Integer.parseInt(eKapasite1.getText());
                float ure =  Float.parseFloat(uretim1.getText());

                // Veri girişlerinde boş ya da hatalı veri kontrolü
                if (isim == null || isim.trim().isEmpty())
                    throw new IllegalArgumentException("Kaynak ismi boş olamaz!"); // Bina ismi eksik veya yanlış girilmiş

                if (kapasite <= 0) 
                    throw new IllegalArgumentException("Kapasite 0 veya negatif olamaz!"); // Kapasite hatalı

                if (ure < 0) 
                    throw new IllegalArgumentException("Enerji üretimi negatif olamaz!"); // Tüketim değerleri doğru değil
                
                switch ((String) kaynakListesiModel.getValueAt(selectedRow, 4)) {
                    case "Güneş" -> kaynak = new Gunes(isim, konum, kapasite, ure);
                    case "Rüzgar" -> kaynak = new Ruzgar(isim, konum, kapasite, ure);
                    case "Fosil" -> kaynak = new Fosil(isim, konum, kapasite, ure);
                    case "Nükleer" -> kaynak = new Nukleer(isim, konum, kapasite, ure);
                    default -> throw new IllegalArgumentException("Kaynak türü geçersiz!"); // Geçersiz bina türü hatası
                }
                
                enerjikaynaklari.remove(enerjikaynaklari.size() - 1);
                enerjikaynaklari.set(selectedRow, kaynak);
                
                kaynakListesiModel.setRowCount(0); // Clear the table

                for (Enerjikaynagi e : enerjikaynaklari) {
                    kaynakListesiModel.addRow(new Object[] {
                        e.getIsim(),
                        e.getKonum(),
                        e.getKapasite(),
                        e.getUretim(),
                        e.getTip()
                    });
                }
                JOptionPane.showMessageDialog(this, "Kaynak başarıyla güncellendi", "Başarılı Işlem", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                // Sayısal bir değer beklenirken geçersiz bir giriş yapıldığında
                JOptionPane.showMessageDialog(this, "Lütfen geçerli bir sayı girin!", "Hata", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                // Geçersiz bina türü gibi durumlarda
                JOptionPane.showMessageDialog(this, e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Diğer beklenmeyen hatalar
                JOptionPane.showMessageDialog(this, "Bilinmeyen bir hata oluştu: ", "Hata", JOptionPane.ERROR_MESSAGE);
            }
            } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir satır seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_eGunActionPerformed

    private void eIsim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIsim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIsim1ActionPerformed

    private void uretim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uretim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uretim1ActionPerformed

    private void kaynakListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaynakListMouseClicked
        // TODO add your handling code here:
        int selectedRow = kaynakList.getSelectedRow();
        if (selectedRow != -1) {
            eIsim1.setText(kaynakListesiModel.getValueAt(selectedRow, 0).toString());
            eKonum1.setSelectedItem(kaynakListesiModel.getValueAt(selectedRow, 1).toString());
            eKapasite1.setText(kaynakListesiModel.getValueAt(selectedRow, 2).toString());
            uretim1.setText(kaynakListesiModel.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_kaynakListMouseClicked

    private void eSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSilActionPerformed
        // TODO add your handling code here:
        int selectedRow = kaynakList.getSelectedRow();
        if (selectedRow != -1) {       
            enerjikaynaklari.remove(selectedRow);
            kaynakListesiModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Kayanak başarıyala silindi!", "Başarılı Işlem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir satır seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynaklariListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynaklariListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynaklariListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnerjiKaynaklariListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnerjiKaynaklariListesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eEkle;
    private javax.swing.JButton eGun;
    private javax.swing.JTextField eIsim;
    private javax.swing.JTextField eIsim1;
    private javax.swing.JTextField eKapasite;
    private javax.swing.JTextField eKapasite1;
    private javax.swing.JTextField eKonum;
    private javax.swing.JComboBox<String> eKonum1;
    private javax.swing.JButton eSil;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable kaynakList;
    private javax.swing.JTextField uretim;
    private javax.swing.JTextField uretim1;
    // End of variables declaration//GEN-END:variables
}
